# Generated by Django 5.1 on 2024-08-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_profile_email_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='pais',
        ),
    ]
